### ISSUE TITLE
LINK_POS_LEFT missing from Const.js

### ISSUE THREAD

**Issue by vnehess** [guiqui/react-timeline-gantt#11]
I think LINK_POS_LEFT is missing from the Const.js file, not sure what it should be

**Comment by guiqui** [comment]
Hi there, the LINK_POS_LEFT,LINK_POS_RIGHT  should be deprecated since the  position of the task  is no used anymore.We need to do a bit of clean up!

**Comment by vnehess** [comment]
got it, thanks
