### ISSUE TITLE
Cannot make task name in the task list non editable

### ISSUE THREAD

**Issue by ericreis** [guiqui/react-timeline-gantt#19]
Hi,

I was trying to use this component but in my use case, I cannot allow the user to edit the task name by clicking it. I looked at the code and saw that this is not currently possible. 

@guiqui is this repository still maintained? I would gladly open a PR to make this configuration possible, but I haven't seen much activity lately here.

**Comment by guiqui** [comment]
Hi Eric,
Yes the repo still maintained. Please do a PR a will review it.Thanks.
