### ISSUE TITLE
Edit Header with only years and months

### ISSUE THREAD

**Issue by HachimInno** [guiqui/react-timeline-gantt#2]
Hello, I would like to know if it's possible using the config object maybe or something else, to show in the header the years and 12 months under them instead of the months and 30 days under them ?

thanks !

**Comment by guiqui** [comment]
HI there, looks like I forgot to include the "year" option in the mode property.I going to create an issue and fix it. It should be trivial.It will be available in the next release.Should not take long!

**Comment by HachimInno** [comment]
Alright, looking forward to it. Thank you so much !

**Comment by guiqui** [comment]
Hi just release a new version 0.3.9 with year mode enabled.

**Comment by guiqui** [comment]
> Alright, looking forward to it. Thank you so much !

I have just added year mode in version 0.3.9
