### ISSUE TITLE
Rest Api Call

### ISSUE THREAD

**Issue by nvgopi** [guiqui/react-timeline-gantt#24]
Hey, 

Thanks for the react-timeline-gantt. Was wondering if there is any sample with a rest api call to fetch data?

**Comment by nvgopi** [comment]
Sorry.. its more of a question and not an issue.

**Comment by guiqui** [comment]
Hi there,
No I don't  have an example  with a rest api, but if you take a look at the
redux example you just need to modify the actions
and add http or fetch in the right place.
