### ISSUE TITLE
Customisation of components

### ISSUE THREAD

**Issue by kevinhury** [guiqui/react-timeline-gantt#38]
Hello,
I would like to have a way to fully customize some of the components. For example inserting a row with 3 inputs inside the taskList section.
something like this:

```js
const config = {
  taskList: {
    title: {
      label: "Task Todo",
      style: {
        background: "linear-gradient( grey, black)"
      }
    },
    task: (props) => <CustomTaskComponent {...props} />,
  },
};
```

If this is not supported, I don't mind implementing this myself and open a pull request for it.
Wondering if this project is still active.

Thanks

**Comment by mrkchang** [comment]
Did you end up implementing this?

**Comment by alonbentura** [comment]
it is work now?
