### ISSUE TITLE
Can't resolve 'react-sizeme'

### ISSUE THREAD

**Issue by Fi1osof** [guiqui/react-timeline-gantt#9]

**Comment by xzessmedia** [comment]
Using this component you should be familiar with npm...
npm -i react-sizeme --save

**Comment by guiqui** [comment]
Thank you xzessmedia, 
Does not a npm i do the job? 
It should be part of the package.json

**Comment by Fi1osof** [comment]
@guiqui it's peerDependencies, nor dependencies and not install on install react-timeline-gantt as dependency.
